API-638
bliblidotcom/seller-api-client-php pull request #1
Opened 2020-04-28 07:30 UTC by zulffaza

2020-04-28 08:09 UTC, Agie-ghazy-falah requested changes
need code improvement

2020-04-28 08:09 UTC, Agie-ghazy-falah commented on index-basic-auth.php
> +		echo "string";
remove unused codes

2020-04-28 08:09 UTC, Agie-ghazy-falah commented on index-basic-auth.php
> +	$config->setSignatureKey("secret"); //your API secret key
//your API secret key, it's optional depends on the selected seller choice

2020-04-28 08:09 UTC, Agie-ghazy-falah commented on index-basic-auth.php
> +	echo $response;
change to fulfill order v2

2020-04-28 08:09 UTC, Agie-ghazy-falah commented on invoker/basic_auth/invoke_get.php
> +		. "&username=" . $request->getMtaUsername()
&sellerCode also

2020-04-28 08:09 UTC, Agie-ghazy-falah commented on invoker/basic_auth/invoke_get.php
> +	    "username: " . $request->getMtaUsername(),
no need to set this header for basic auth flow

2020-04-28 08:09 UTC, Agie-ghazy-falah commented on invoker/basic_auth/invoke_post.php
> +		. "&username=" . $request->getMtaUsername()
&sellerCode also

2020-04-28 08:09 UTC, Agie-ghazy-falah commented on invoker/basic_auth/invoke_post.php
> +<?php
is this class for all method type with body request? if yes, change class name to invoke_with_body.php

2020-04-28 08:09 UTC, Agie-ghazy-falah commented on invoker/invoke_post.php
>  <?php
change to invoke_with_body.php

2020-04-28 08:09 UTC, Agie-ghazy-falah commented on invoker/invoke_get.php
>  <?php
change to invoke_without_body.php

2020-04-28 08:09 UTC, Agie-ghazy-falah commented on invoker/basic_auth/invoke_get.php
> +<?php
change to invoke_without_body.php if this class is used for DELETE method also

2020-04-28 09:17 UTC, zulffaza commented on invoker/basic_auth/invoke_get.php
> +		. "&username=" . $request->getMtaUsername()
It's storeCode not sellerCode

2020-04-29 04:36 UTC, Agie-ghazy-falah approved these changes

2020-04-29 06:24 UTC, merged